# TensorFlow Basics

In [1]:
import tensorflow as tf

In [2]:
# Make sure you are using 1.3 for exact sytnax matching!
print(tf.__version__)

2.7.0


## Tensors

In [3]:
hello = tf.constant('Hello')

In [7]:
print(hello)
print(type(hello))

tf.Tensor(b'Hello', shape=(), dtype=string)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [8]:
world = tf.constant('World')

print(world)
print(type(world))

tf.Tensor(b'World', shape=(), dtype=string)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [11]:
result = hello +" "+ world

print(result)
print(type(result))

tf.Tensor(b'Hello World', shape=(), dtype=string)
<class 'tensorflow.python.framework.ops.EagerTensor'>


** Computations **

In [16]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

print(tensor_1)
print(type(tensor_1))
print(tensor_2)
print(type(tensor_2))

tf.Tensor(1, shape=(), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(2, shape=(), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [17]:
print(tensor_1 + tensor_2)

tf.Tensor(3, shape=(), dtype=int32)


## Operations

In [25]:
const = tf.constant(10)

print(const)

tf.Tensor(10, shape=(), dtype=int32)


In [26]:
fill_mat = tf.fill((4,4),10)

print(fill_mat)

print(type(fill_mat))

tf.Tensor(
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]], shape=(4, 4), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [27]:
myzeros = tf.zeros((4,4))

print(myzeros)

print(type(myzeros))

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(4, 4), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [28]:
myones = tf.ones((4,4))

print(myones)

print(type(myones))

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(4, 4), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [31]:
my_ops = [const,fill_mat,myzeros,myones]

print(my_ops)

print(type(my_ops))

[<tf.Tensor: shape=(), dtype=int32, numpy=10>, <tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]], dtype=int32)>, <tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>, <tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>]
<class 'list'>


## Matrix Multiplication

In [36]:
a = tf.constant([ [1,2],
                  [3,4] ])

print(a)

print(a.get_shape())

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
(2, 2)


In [37]:
b = tf.constant([[10],[100]])

print(b)
print(b.get_shape())

tf.Tensor(
[[ 10]
 [100]], shape=(2, 1), dtype=int32)
(2, 1)


In [40]:
result = tf.matmul(a,b)

print(result)

print(result.get_shape())

tf.Tensor(
[[210]
 [430]], shape=(2, 1), dtype=int32)
(2, 1)
